// This file is auto-generated by scripts/generate-meta-config.js
// Do not edit manually - edit public/.well-known/farcaster.json instead

export const META_CONFIG = {
  "title": "Farcaster Mini App",
  "description": "Welcome to Remix!",
  "farcasterMiniapp": {
    "version": "1",
    "imageUrl": "https://d80c31df46e5.ngrok.app/images/flux-embed-2025-08-17T06-45-06-151Z.png",
    "button": {
      "title": "Launch App",
      "action": {
        "type": "launch_miniapp",
        "name": "Farcaster Mini App",
        "url": "https://d80c31df46e5.ngrok.app",
        "splashImageUrl": "https://d80c31df46e5.ngrok.app/images/flux-splash-2025-08-17T06-45-16-598Z.png",
        "splashBackgroundColor": "#0ea5e9"
      }
    }
  },
  "config": {
    "version": "1",
    "name": "Farcaster Mini App",
    "iconUrl": "https://d80c31df46e5.ngrok.app/images/flux-icon-2025-08-17T06-44-53-003Z.png",
    "homeUrl": "https://d80c31df46e5.ngrok.app",
    "imageUrl": "https://d80c31df46e5.ngrok.app/images/flux-embed-2025-08-17T06-45-06-151Z.png",
    "buttonTitle": "Launch App",
    "splashImageUrl": "https://d80c31df46e5.ngrok.app/images/flux-splash-2025-08-17T06-45-16-598Z.png",
    "splashBackgroundColor": "#0ea5e9"
  }
} as const;

export type MetaConfig = typeof META_CONFIG;
